Bug #43218: Fix missing import
> # python -m vncautomate.cli hdmi1.knut.univention.de root
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/usr/lib/python2.7/dist-packages/vncautomate/cli.py", line 107, in <module>
>     init_logger(args.log)
> NameError: name 'init_logger' is not defined

Same with python3